import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ChatPanel({ messages, input, onInputChange, onSend, sending, actions, confluenceParentId, onConfluenceParentIdChange, asanaProjectId, onAsanaProjectIdChange, publishUrl, qaSummary, asanaStatus, statusMessage, errorMessage, disabled, }) {
    const handleSubmit = async (event) => {
        event.preventDefault();
        if (!input.trim() || sending || disabled) {
            return;
        }
        await onSend();
    };
    return (_jsxs("div", { className: "panel", children: [_jsx("h2", { children: "Chat & Actions" }), errorMessage && _jsx("div", { className: "error-banner", children: errorMessage }), statusMessage && _jsx("div", { className: "success-banner", children: statusMessage }), _jsxs("section", { children: [_jsx("label", { htmlFor: "confluence-parent", children: "Confluence Parent Page" }), _jsx("input", { id: "confluence-parent", type: "text", placeholder: "Optional parent page ID", value: confluenceParentId, onChange: (event) => onConfluenceParentIdChange(event.target.value) })] }), _jsxs("section", { children: [_jsx("label", { htmlFor: "asana-project", children: "Asana Project ID" }), _jsx("input", { id: "asana-project", type: "text", placeholder: "asana-project-gid", value: asanaProjectId, onChange: (event) => onAsanaProjectIdChange(event.target.value) })] }), _jsx("section", { className: "action-grid", children: actions.map((action) => (_jsx("button", { type: "button", className: action.variant === "secondary" ? "secondary" : "", onClick: () => action.onClick(), disabled: action.disabled || disabled, children: action.label }, action.label))) }), publishUrl && (_jsxs("div", { className: "success-banner", children: ["Published to Confluence:", _jsx("button", { type: "button", className: "link-button", onClick: () => window.open(publishUrl, "_blank", "noopener"), children: "Open Page \u2197" })] })), qaSummary && _jsxs("div", { className: "success-banner", children: ["QA: ", qaSummary] }), asanaStatus && _jsxs("div", { className: "success-banner", children: ["Asana: ", asanaStatus] }), _jsx("div", { className: "chat-messages", children: messages.length === 0 ? (_jsx("span", { className: "small", children: "No messages yet. Ask the planner to update sections." })) : (messages.map((message) => (_jsxs("div", { className: `chat-message ${message.role}`, children: [_jsxs("div", { className: "small", style: { marginBottom: "0.35rem" }, children: [new Date(message.timestamp).toLocaleTimeString([], {
                                    hour: "2-digit",
                                    minute: "2-digit",
                                }), " \u2013 ", message.role === "assistant" ? "Planner" : "You"] }), _jsx("div", { children: message.content })] }, message.id)))) }), _jsxs("form", { onSubmit: handleSubmit, style: { marginTop: "0.75rem" }, children: [_jsx("label", { htmlFor: "chat-message", children: "Chat with Planner" }), _jsx("textarea", { id: "chat-message", placeholder: "Capture latest fixture updates, decisions, or TODOs that need to roll into the plan.", value: input, onChange: (event) => onInputChange(event.target.value), disabled: disabled }), _jsx("button", { type: "submit", disabled: sending || disabled, style: { marginTop: "0.75rem" }, children: sending ? "Sending…" : "Send Message" })] })] }));
}
